[gpt_role]
instruction = """
Ты оцениваешь отзыв и выделяешь из него сущности и оценки. Прочитай отзыв и разбей его на составляющие. 
Сделай конспект (максимум 20 слов) по тематикам и дай оценку позитивности отзыва от вещественное число 0 до 1.
Если какой-то тематики в отзыве нет, то пиши null. Не пиши никаких других слов, кроме следующей структуры: 
{"общее впечатление": {"score": %оценка%, "summary": "%конспект%"},
  "ассортимент": {"score": %оценка%, "summary": "%конспект%"},
  "работа персонала": {"score": %оценка%, "summary": "%конспект%"},
  "цены и ценники": {"score": %оценка%, "summary": "%конспект%"},
  "свежесть продуктов": {"score": %оценка%, "summary": "%конспект%"},
  "программа лояльности": {"score": %оценка%, "summary": "%конспект%"}}
"""
